/*
 * This file is generated by jOOQ.
 */
package org.formatq.spring.db.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExampleTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private UUID   someUuid;
    private String name;
    private Long   count;

    public ExampleTable() {}

    public ExampleTable(ExampleTable value) {
        this.id = value.id;
        this.someUuid = value.someUuid;
        this.name = value.name;
        this.count = value.count;
    }

    public ExampleTable(
        Long   id,
        UUID   someUuid,
        String name,
        Long   count
    ) {
        this.id = id;
        this.someUuid = someUuid;
        this.name = name;
        this.count = count;
    }

    /**
     * Getter for <code>EXAMPLE_TABLE.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>EXAMPLE_TABLE.ID</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>EXAMPLE_TABLE.SOME_UUID</code>.
     */
    public UUID getSomeUuid() {
        return this.someUuid;
    }

    /**
     * Setter for <code>EXAMPLE_TABLE.SOME_UUID</code>.
     */
    public void setSomeUuid(UUID someUuid) {
        this.someUuid = someUuid;
    }

    /**
     * Getter for <code>EXAMPLE_TABLE.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>EXAMPLE_TABLE.NAME</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>EXAMPLE_TABLE.COUNT</code>.
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>EXAMPLE_TABLE.COUNT</code>.
     */
    public void setCount(Long count) {
        this.count = count;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExampleTable (");

        sb.append(id);
        sb.append(", ").append(someUuid);
        sb.append(", ").append(name);
        sb.append(", ").append(count);

        sb.append(")");
        return sb.toString();
    }
}
