/*
 * This file is generated by jOOQ.
 */
package org.formatq.spring.db.jooq;


import org.formatq.spring.db.jooq.tables.ExampleTable;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_EXAMPLE_TABLE_SOME_UUID = Internal.createIndex(DSL.name("IDX_EXAMPLE_TABLE_SOME_UUID"), ExampleTable.EXAMPLE_TABLE, new OrderField[] { ExampleTable.EXAMPLE_TABLE.SOME_UUID }, false);
}
