/*
 * This file is generated by jOOQ.
 */
package org.formatq.spring.db.jooq;


import org.formatq.spring.db.jooq.tables.ExampleTable;
import org.formatq.spring.db.jooq.tables.records.ExampleTableRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExampleTableRecord> CONSTRAINT_4 = Internal.createUniqueKey(ExampleTable.EXAMPLE_TABLE, DSL.name("CONSTRAINT_4"), new TableField[] { ExampleTable.EXAMPLE_TABLE.ID }, true);
}
