/*
 * This file is generated by jOOQ.
 */
package org.formatq.spring.db.jooq;


import org.formatq.spring.db.jooq.tables.ExampleTable;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>EXAMPLE_TABLE</code>.
     */
    public static final ExampleTable EXAMPLE_TABLE = ExampleTable.EXAMPLE_TABLE;
}
